added the front end code from the repo
satya77/Temporal_Tagger_Service pull request #6
Opened 2022-05-25 13:58 UTC by satya77

1. Added the front end code as it is from the gitlab internal repo 
2. Still need to write a readme file 
3. removed the API internal address from the rouets.py (we need to mention it in the documentations) 
4.

2022-05-25 14:10 UTC, dennlinger requested changes
Some additional general comments:

1. Not sure why we have multiple assets of `onlinedating.png` (there is variants called `onlinedating3.png` and so on). Maybe we can remove unused ones?
2. We can probably merge the `requirements.txt` with the backend one.

Otherwise didn't deeply check the quality of the HTML files, but I trust you ;-)

2022-05-25 14:10 UTC, dennlinger commented on front_end/app/routes.py
> +from langdetect import detect
Not sure, but it seems `langdetect` is actually not used here?
In that case, it would be best to remove the commented out code (and dependency) altogether.

2022-05-25 14:10 UTC, dennlinger commented on front_end/app/routes.py
> +            return 'Please choose a mode for the HeidelTime model.', 500
AFAIK, this should be handled by our backend code as well.
Also note that `.split("_")[1]` can crash if the `model_type` has no specified mode in the name.

You can either use `.split("_")[-1]` (which is "safe"), or alternatively levae this to the backend code, which will default to "NARRATIVES" if unspecified.

2022-05-25 14:10 UTC, dennlinger commented on front_end/requirements.txt
> +langdetect
Remove as specified in above comments (unless used elsewhere).

2022-05-30 07:57 UTC, satya77 commented
The requirements are merged and the unnecessary code for heideltime and langdetect are removed. 
`onlinedating.png` is reduced to a single one.

2022-05-30 08:08 UTC, merged